# tomcat设置
server:
  port: 9090
  servlet:
    context-path: /api

# spring设置
spring:
  application:
    name: application
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: com.example.Student.*.entity
  mapper-locations:
    - classpath*:com/example/Student/module/*/mapper/xml/*.xml