# tomcat设置
server:
  port: 9090
  servlet:
    context-path: /api
# spring设置
spring:
  application:
    name: application
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  type-aliases-package: com.example.Student.studentinfo.entity
  mapper-locations:
    - classpath*:com/example/Student/mapper/xml/mapper.xml